// Generated by dia2code
#ifndef __ETATS__H
#define __ETATS__H

#include "Etats/Temps.h"
#include "Etats/Race.h"
#include "Etats/EtatAnimal.h"
#include "Etats/Animal.h"
#include "Etats/EtatElevage.h"
#include "Etats/Elevage.h"
#include "Etats/Ferme.h"
#include "Etats/ChangementEtatsID.h"
#include "Etats/NotificationChangementEtat.h"
#include "Etats/EtatsObserver.h"
#include "Etats/AnimalFemelle.h"
#include "Etats/AnimalMale.h"
#endif
