// Generated by dia2code
#ifndef MOTEUR__COMMANDENOUVELLEBETE__H
#define MOTEUR__COMMANDENOUVELLEBETE__H

#include <memory>
#include <string>
#include <vector>

namespace Etats {
  class Ferme;
  class Elevage;
};
namespace moteur {
  class Commande;
}

#include "Etats/Ferme.h"
#include "Etats/Elevage.h"
#include "Commande.h"

namespace moteur {

  /// class CommandeNouvelleBete - 
  class CommandeNouvelleBete : public moteur::Commande {
    // Attributes
  protected:
    std::shared_ptr<Etats::Ferme> ferme;
    std::shared_ptr<Etats::Elevage> elevage;
    bool sexe;
    int mois;
    int annee;
    std::vector<std::string> ancetres;
    // Operations
  public:
    CommandeNouvelleBete ();
    CommandeNouvelleBete (std::shared_ptr<Etats::Ferme> frm, std::shared_ptr<Etats::Elevage> elvaj, bool sx, int ms, int an, std::vector<std::string> anc);
    ~CommandeNouvelleBete ();
    void effectuerCommande ();
  };

};

#endif
