// Generated by dia2code
#ifndef MOTEUR__PASSERMOISSUIVANT__H
#define MOTEUR__PASSERMOISSUIVANT__H

#include <memory>

namespace Etats {
  class Temps;
  class Ferme;
};
namespace moteur {
  class Commande;
}

#include "Etats/Temps.h"
#include "Etats/Ferme.h"
#include "Commande.h"

namespace moteur {

  /// class PasserMoisSuivant - 
  class PasserMoisSuivant : public moteur::Commande {
    // Attributes
  protected:
    //std::shared_ptr<Etats::Temps> temps;
    std::shared_ptr<Etats::Ferme> ferme;
    // Operations
  public:
    PasserMoisSuivant ();
    PasserMoisSuivant (std::shared_ptr<Etats::Ferme> ferme);
    ~PasserMoisSuivant ();
    void effectuerCommande ();
  };

};

#endif
