// Generated by dia2code
#ifndef SOLUTION__SERVICEEXCEPTION__H
#define SOLUTION__SERVICEEXCEPTION__H


namespace solution {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace solution {

  /// class ServiceException - 
  class ServiceException {
    // Associations
    solution::HttpStatus httpStatus;
    // Attributes
  protected:
    string msg;
    // Operations
  public:
    ServiceException (HttpStatus status, string msg);
    HttpStatus status () const;
    const char* what () const;
  };

};

#endif
