// Generated by dia2code
#ifndef SOLUTION__USERDB__H
#define SOLUTION__USERDB__H


namespace solution {
  class User;
}

#include "User.h"

namespace solution {

  /// class UserDB - 
  class UserDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    map<int,unique_ptr<User> > users;
    // Operations
  public:
    UserDB ();
    const User* getUser (int id) const;
    int addUser (unique_ptr<User> user);
    void setUser (int id, unique_ptr<User> user);
    void removeUser (int id);
  };

};

#endif
