// Generated by dia2code
#ifndef SOLUTION__USER__H
#define SOLUTION__USER__H


namespace solution {

  /// class User - 
  class User {
    // Attributes
  public:
    string name;
    int age;
    // Operations
  public:
    User (string name, int age);
  };

};

#endif
