// Generated by dia2code
#ifndef SOLUTION__VERSIONSERVICE__H
#define SOLUTION__VERSIONSERVICE__H


namespace solution {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace solution {

  /// class VersionService - 
  class VersionService : public solution::AbstractService {
    // Operations
  public:
    VersionService ();
    HttpStatus get (Json::Value& out, int id) const;
  };

};

#endif
