// Generated by dia2code
#ifndef __RENDU__H
#define __RENDU__H

//#include "Rendu/FenetreNouvelleRace : public QWidget.h"
//#include "Rendu/FenetreNouvelElevage : public QWidget.h"
//#include "Rendu/FenetreNouvelleBete : public QWidget.h"
//#include "Rendu/FenetrePrincipale : public QMainWindow.h"
#endif
