// Generated by dia2code
#ifndef ETATS__ANIMALMALE__H
#define ETATS__ANIMALMALE__H

#include <memory>
#include <string>
#include <vector>

namespace Etats {
  class Elevage;
  class AnimalFemelle;
  class Animal;
}

#include "Elevage.h"
#include "Animal.h"

namespace Etats {

  /// class AnimalMale - 
  class AnimalMale : public Etats::Animal {
    // Operations
  public:
    AnimalMale ();
    AnimalMale (std::shared_ptr<Elevage> elvaj, int ms, int an, std::vector<std::string> ancet);
    //~AnimalMale ();
    //void tuerAnimalMale ();
    //void vendreAnimal ();
    bool accoupler (AnimalFemelle* femelle);
  };

};

#endif
