// Generated by dia2code
#ifndef ETATS__ANIMALFEMELLE__H
#define ETATS__ANIMALFEMELLE__H

#include <array>
#include <memory>
#include <string>
#include <vector>

namespace Etats {
  class Animal;
  class Elevage;
  class AnimalMale;
}

#include "Animal.h"
#include "Elevage.h"

namespace Etats {

  /// class AnimalFemelle - 
  class AnimalFemelle : public Etats::Animal {
    // Attributes
  private:
    bool isEnceinte = false;
    std::array<int,2> dateAccouplement;
    std::shared_ptr<Animal> geniteur;
    std::array<int,2> dateDerniereMiseBas;
    // Operations
  public:
    AnimalFemelle ();
    AnimalFemelle (std::shared_ptr<Elevage> elvaj, int ms, int an, std::vector<std::string> ancet);
    //~AnimalFemelle ();
    //void tuerAnimal ();
    //void vendreAnimal ();
    std::array<int,2> getDateDerniereMiseBas ();
    bool accoupler (AnimalMale* male);
    bool mettreBas ();
  };

};

#endif
