// Generated by dia2code
#ifndef ETATS__CHANGEMENTETATSID__H
#define ETATS__CHANGEMENTETATSID__H


namespace Etats {

  enum ChangementEtatsID {
    TOUT_CHANGE     = 0,
    LISTE_ELEVAGE_CHANGE     = 1,
    BUDGET_TEMPS_CHANGE     = 2,
    ELEVAGE_CHANGE     = 3
  };

};

#endif
