// Generated by dia2code
#ifndef ETATS__NOTIFICATIONCHANGEMENTETAT__H
#define ETATS__NOTIFICATIONCHANGEMENTETAT__H

#include <memory>

namespace Etats {
  class Ferme;
};
namespace Rendu {
  class FenetrePrincipale;
}

#include "Ferme.h"
#include "Rendu/FenetrePrincipale.h"
#include "ChangementEtatsID.h"

namespace Etats {

  /// class NotificationChangementEtat - 
  class NotificationChangementEtat {
    // Associations
    Etats::ChangementEtatsID id;
    // Attributes
  private:
    std::shared_ptr<Ferme> ferme;
    Rendu::FenetrePrincipale *fenetrePrincipale;
    // Operations
  public:
    NotificationChangementEtat ();
    NotificationChangementEtat (ChangementEtatsID etatNotif, std::shared_ptr<Ferme> frm, Rendu::FenetrePrincipale *fenPrincipale);
    ~NotificationChangementEtat ();
    void actualiserChangementRendu ();
    //std::shared_ptr<Elevage> getPtrElevage ();
    int getIDNotification ();
  };

};

#endif
