// Generated by dia2code
#ifndef ETATS__RACE__H
#define ETATS__RACE__H

#include <string>
#include <array>

namespace Etats {

  /// class Race - 
  class Race {
    // Attributes
  private:
    std::string idRace;
    std::string nomRace;
    std::array<int, 2> esperanceDeVie;
    std::array<int,2> poidsMoyenAdulte;
    std::array<int, 2> ageMoyenMaturite;
    std::array<double, 2> prixNourritureVeterinaireParKilo;
    int dureeGestation;
    int dureeEntre2Grossesses;
    int nbEnfantsPortee;
    int poidsMoyenNaissance;
    double prixVenteKilo;
    int nbGenerations;
    /// totalise le nombre d'ancêtres à stocker dans le patrimoine génétique, à partir du nombre de générations
    int nbAncetres;
    // Operations
  public:
    Race ();
    Race (std::string nom, int esperanceDeVieMale, int esperanceDeVieFemelle, int poidsMoyenAdulteMale, int poidsMoyenAdulteFemelle, int ageMoyenMaturiteMale, int ageMoyenMaturiteFemelle, double prixNourritureVeterinaireParKiloMale, double prixNourritureVeterinaireParKiloFemelle, int dureeGest, int dureeEntre2Gross, int nbEnfants, int poidsNaissance, double prixVenteKg, int nbGen);
    ~Race ();
    std::string getIDRace ();
    std::string getNomRace ();
    int getEsperanceDeVie (bool sexe);
    int getPoidsMoyenAdulte (bool sexe);
    int getAgeMoyenMaturite (bool sexe);
    double getPrixNourritureVeterinaireParKilo (bool sexe);
    int getDureeGestation ();
    int getDureeEntre2Grossesses ();
    int getNbEnfantsPortee ();
    int getPoidsMoyenNaissance ();
    double getPrixVenteKilo ();
    int getNbGenerations ();
    int getNbAncetres ();
    void setNomRace (std::string& nom);
    void setEsperanceDeVie (bool sexe, int duree_esperancedevie);
    void setPoidsMoyenAdulte (bool sexe, int poids);
    void setAgeMoyenMaturite (bool sexe, int age);
    void setPrixNourritureVeterinaireParKilo (bool sexe, double prix);
    void setDureeGestation (int duree);
    void setDureeEntre2Grossesses (int duree);
    void setNbEnfantsPortee (int nbEnfantsPortee);
    void setPoidsMoyenNaissance (int poids);
    void setPrixVenteKilo (double prix);
    void setNbGenerations (int nbGen);
  };

};

#endif
