// Generated by dia2code
#ifndef ETATS__TEMPS__H
#define ETATS__TEMPS__H

#include <string>
#include <array>

namespace Etats {

  /// class Temps - 
  class Temps {
    // Attributes
  private:
    int annee = 2016;
    int mois = 1;
    std::array<std::string, 12> nomMois;
    // Operations
  public:
    Temps ();
    Temps (int m, int a);
    int getAnnee ();
    int getMois ();
    void setAnnee (int annee);
    void setMois (int mois);
    void upAnnee ();
    void upMois ();
    std::array<std::string, 12> getNomMois ();
  };

};

#endif
