// Generated by dia2code
#ifndef __MOTEUR__H
#define __MOTEUR__H

#include "moteur/Commande.h"
#include "moteur/Moteur.h"
#include "moteur/CommandeVendreBete.h"
#include "moteur/PasserMoisSuivant.h"
#include "moteur/CommandeNouvelElevage.h"
#include "moteur/CommandeAccouplerBete.h"
#include "moteur/CommandeNouvelleBete.h"
#include "moteur/CommandeInitialiserFermeTemps.h"
#endif
