// Generated by dia2code
#ifndef __SOLUTION__H
#define __SOLUTION__H

#include "solution/HttpStatus.h"
#include "solution/AbstractService.h"
#include "solution/User.h"
#include "solution/UserDB.h"
#include "solution/UserService.h"
#include "solution/VersionService.h"
#include "solution/ServiceException.h"
#include "solution/ServicesManager.h"
#endif
