// Generated by dia2code
#ifndef MOTEUR__COMMANDENOUVELELEVAGE__H
#define MOTEUR__COMMANDENOUVELELEVAGE__H

#include <string>
#include <memory>

namespace Etats {
  class Race;
  class Temps;
  class Ferme;
  class EtatsObserver;
};
namespace Rendu {
  class FenetrePrincipale;
};
namespace moteur {
  class Commande;
}

#include "Etats/Race.h"
#include "Etats/Temps.h"
#include "Etats/Ferme.h"
#include "Etats/EtatsObserver.h"
#include "Rendu/FenetrePrincipale.h"
#include "Commande.h"

namespace moteur {

  /// class CommandeNouvelElevage - 
  class CommandeNouvelElevage : public moteur::Commande {
    // Attributes
  private:
    std::string nom;
    std::shared_ptr<Etats::Race> race;
    //std::shared_ptr<Etats::Temps> temps;
    std::shared_ptr<Etats::Ferme> ferme;
    std::shared_ptr<Etats::EtatsObserver> observer;
    Rendu::FenetrePrincipale *fenetrePrincipale;
    // Operations
  public:
    CommandeNouvelElevage ();
    CommandeNouvelElevage (std::shared_ptr<Etats::Ferme> frm, std::string nm, std::shared_ptr<Etats::Race> rac, Rendu::FenetrePrincipale *fenPrincipale, std::shared_ptr<Etats::EtatsObserver> observ);
    ~CommandeNouvelElevage ();
    void effectuerCommande ();
  };

};

#endif
