// Generated by dia2code
#ifndef MOTEUR__COMMANDE__H
#define MOTEUR__COMMANDE__H


namespace moteur {

  /// class Commande - 
  class Commande {
    // Operations
  public:
    virtual ~Commande ();
    virtual void effectuerCommande () = 0;
  };

};

#endif
