// Generated by dia2code
#ifndef MOTEUR__COMMANDEVENDREBETE__H
#define MOTEUR__COMMANDEVENDREBETE__H

#include <memory>

namespace Etats {
  class Animal;
  class Ferme;
};
namespace moteur {
  class Commande;
}

#include "Etats/Animal.h"
#include "Etats/Ferme.h"
#include "Commande.h"

namespace moteur {

  /// class CommandeVendreBete - 
  class CommandeVendreBete : public moteur::Commande {
    // Attributes
  protected:
    std::shared_ptr<Etats::Animal> animal;
    std::shared_ptr<Etats::Ferme> ferme;
    // Operations
  public:
    CommandeVendreBete ();
    CommandeVendreBete (std::shared_ptr<Etats::Ferme> frm, std::shared_ptr<Etats::Animal> anm);
    ~CommandeVendreBete ();
    void effectuerCommande ();
  };

};

#endif
