// Generated by dia2code
#ifndef MOTEUR__COMMANDEAFFICHERFENETRE__H
#define MOTEUR__COMMANDEAFFICHERFENETRE__H

#include <memory>
#include <QWidget>

namespace Etats {
  class Ferme;
  class Temps;
};
class QWidget;
namespace moteur {
  class Commande;
}

#include "Etats/Ferme.h"
#include "Etats/Temps.h"
#include "Commande.h"

namespace moteur {

  /// class CommandeAfficherFenetre - 
  class CommandeAfficherFenetre : public moteur::Commande {
    // Attributes
  protected:
    std::shared_ptr<Etats::Ferme> ferme;
    //std::shared_ptr<Etats::Temps> temps;
    QWidget* fenetre;
    // Operations
  public:
    CommandeAfficherFenetre ();
    CommandeAfficherFenetre (std::shared_ptr<Etats::Ferme> frm, QWidget* fen);
    ~CommandeAfficherFenetre ();
    void effectuerCommande ();
  };

};

#endif
