// Generated by dia2code
#ifndef MOTEUR__COMMANDEINITIALISERFERMETEMPS__H
#define MOTEUR__COMMANDEINITIALISERFERMETEMPS__H

#include <memory>

namespace Etats {
  class Ferme;
  class Temps;
};
namespace Rendu {
  class FenetrePrincipale;
};
namespace Etats {
  class EtatsObserver;
};
namespace moteur {
  class Commande;
}

#include "Etats/Ferme.h"
#include "Etats/Temps.h"
#include "Rendu/FenetrePrincipale.h"
#include "Etats/EtatsObserver.h"
#include "Commande.h"

namespace moteur {

  /// class CommandeInitialiserFermeTemps - 
  class CommandeInitialiserFermeTemps : public moteur::Commande {
    // Attributes
  protected:
    std::shared_ptr<Etats::Ferme> ferme;
    //std::shared_ptr<Etats::Temps> temps;
    double budget;
    double emprunts;
    int mois;
    int annee;
    Rendu::FenetrePrincipale *fenetrePrincipale;
    std::shared_ptr<Etats::EtatsObserver> observer;
    // Operations
  public:
    CommandeInitialiserFermeTemps ();
    CommandeInitialiserFermeTemps (std::shared_ptr<Etats::Ferme> frm, double bud, double empr, int ms, int an, Rendu::FenetrePrincipale *fenPrincipale, std::shared_ptr<Etats::EtatsObserver> obs);
    ~CommandeInitialiserFermeTemps ();
    void effectuerCommande ();
  };

};

#endif
