// Generated by dia2code
#ifndef MOTEUR__MOTEUR__H
#define MOTEUR__MOTEUR__H

#include <list>
#include <memory>
#include <mutex>

namespace moteur {
  class Commande;
};
namespace Etats {
  class Ferme;
  class Temps;
};
namespace Rendu {
  class FenetrePrincipale;
}

#include "Commande.h"
#include "Etats/Ferme.h"
#include "Etats/Temps.h"
#include "Rendu/FenetrePrincipale.h"

namespace moteur {

  /// class Moteur - 
  class Moteur {
    // Associations
    // Attributes
  private:
    std::list<std::shared_ptr<Commande>> mesCommandes;
    std::mutex corentinFDP;
    // Operations
  public:
    Moteur ();
    void ajouterCommande (std::shared_ptr<Commande> com);
    //void execCommande (std::shared_ptr<Etats::Ferme> frm, std::shared_ptr<Etats::Temps> tps, Rendu::FenetrePrincipale *fenetrePpale);
    void execCommande ();
  };

};

#endif
