// Generated by dia2code
#ifndef RENDU__FENETREPRINCIPALE__H
#define RENDU__FENETREPRINCIPALE__H

#include <QMainWindow>
#include <QListWidget>
#include <memory>
#include <QLabel>
#include <QStackedLayout>
#include <string>
#include <QStatusBar>
#include <QMenu>
#include <QString>
#include <QAction>
#include <QPushButton>
#include <QWidget>

namespace Etats {
  class Ferme;
  class Temps;
};
namespace moteur {
  class Moteur;
};
namespace Rendu {
  class FenetreNouvelElevage;
  class FenetreNouvelleRace;
};
namespace Etats {
  class Elevage;
};
class QObject;
class QWidget;
class QMainWindow;
#include "Etats/Ferme.h"
#include "Etats/Temps.h"
#include "moteur/Moteur.h"
#include "FenetreNouvelElevage.h"
#include "FenetreNouvelleRace.h"
#include "Etats/Elevage.h"

namespace Rendu {

  /// class FenetrePrincipale - 
  class FenetrePrincipale : public QMainWindow {
    // Attributes
  public:
     Q_OBJECT //;
    QListWidget *listeElevage;
  private:
    std::shared_ptr<Etats::Ferme> ferme;
    //std::shared_ptr<Etats::Temps> temps;
    std::shared_ptr<moteur::Moteur> moteu;
    QLabel* texteStatusBar2 = new QLabel("", this, Qt::FramelessWindowHint);
    QLabel* texteStatusBar3 = new QLabel("", this, Qt::FramelessWindowHint);
    FenetreNouvelElevage *fenetreNouvelElevage;
    FenetreNouvelleRace *fenetreNouvelleRace;
    QStackedLayout *stackedLayout;
    // Operations
  public:
    FenetrePrincipale ();
    FenetrePrincipale (std::shared_ptr<Etats::Ferme> frm, std::shared_ptr<moteur::Moteur> mot, FenetreNouvelleRace *fenNouvRace, FenetreNouvelElevage *fenNouvElevage);
    ~FenetrePrincipale ();
    void addItemListeElevage (const std::string &nomElevage);
    void addItemListeElevage (std::shared_ptr<Etats::Elevage> e);
    void addItemListeElevage ();
    void setTexteStatusBar2 (std::string texte);
    void setTexteStatusBar3 (std::string texte);
    void clearListeElevage ();
    QListWidget* getListeElevage ();
  private:
    void creationMenuBar ();
    QStatusBar* creationStatusBar ();
    QMenu*  creationMenu (QMenu * menuPere, const QString& nomMenuFils);
    QAction* creationActionDansMenu (QMenu* menuPere, const QString& nomAction, QObject* parent, const QKeySequence& shortcut, const char* signal, const QObject* receiver, const char* method);
    QAction* creationActionDansMenu (QMenu* menuPere, const QString& nomAction, QObject* parent, const char* signal, const QObject* receiver, const char* method);
    void creationZoneCentrale ();
    QPushButton* creationBoutonDansLayout (const QString& nom, QWidget* widgetParent, QLayout* layoutParent, const char* signal, QObject* receiver, const char* slot, bool enabled);
    void creationToolBar ();
    public slots : void nouvelElevage ();
  };

};

#endif
