// Generated by dia2code
#ifndef RENDU__FENETRENOUVELLERACE__H
#define RENDU__FENETRENOUVELLERACE__H

#include <QWidget>
#include <memory>
#include <QPushButton>
#include <QString>

namespace Etats {
  class Ferme;
  class Temps;
};
namespace moteur {
  class Moteur;
};
class QWidget;
class QObject;
#include "Etats/Ferme.h"
#include "Etats/Temps.h"
#include "moteur/Moteur.h"

namespace Rendu {

  /// class FenetreNouvelleRace - 
  class FenetreNouvelleRace : public QWidget {
    // Attributes
  private:
     Q_OBJECT //;
    std::shared_ptr<Etats::Ferme> ferme;
    //std::shared_ptr<Etats::Temps> temps;
    std::shared_ptr<moteur::Moteur> moteu;
    // Operations
  public:
    FenetreNouvelleRace ();
    FenetreNouvelleRace (std::shared_ptr<Etats::Ferme> frm, std::shared_ptr<moteur::Moteur> mot);
    ~FenetreNouvelleRace ();
    QPushButton* creationBoutonDansLayout (const QString& nom, QWidget* widgetParent, QLayout* layoutParent, const char* signal, QObject* receiver, const char* slot, bool enabled);
  };

};

#endif
