// Generated by dia2code
#ifndef RENDU__FENETRENOUVELLEBETE__H
#define RENDU__FENETRENOUVELLEBETE__H

#include <QWidget>

class QWidget;

namespace Rendu {

  /// class FenetreNouvelleBete - 
  class FenetreNouvelleBete : public QWidget {
    // Operations
  public:
    FenetreNouvelleBete ();
    ~FenetreNouvelleBete ();
  };

};

#endif
