// Generated by dia2code
#ifndef ANIMAL__HPP
#define ANIMAL__HPP

#include "librairiesQt.hpp"
#include "Elevage.hpp"
/// class Animal - 
class Animal {
  // Attributes
private:
  int const IDanimal;
  int IDelevage;
  //Elevage* IDelevage;//Parent;
  //std::shared_ptr<Elevage> IDelevage;
  //char[15] nomAnimal;
  bool sexe;
  /// c'est la date de naissance, comme ca on calcule l'age, au lieu d'incrémenter à tous les coups l'âge
  std::array<int, 2> dateNaissance;
  int poids;
  std::vector<int> ancetres;
  // Operations
public:
  Animal ();
  ~Animal ();
  void tuerAnimal ();
  void vendreAnimal ();
  int getIDAnimal ();
  int getIDElevage ();
  void setIDElevage (int ID);
  //String getNomAnimal ();
  //void setNomAnimal (string nom);
  bool getSexe ();
  void setSexe (bool sexe);
  std::array<int, 2> getDateNaissance ();
  void setDateNaissance (int anneeNaissance, int moisNaissance);
  int getPoids ();
  void setPoids (int poids);
  std::vector<int> getAncetres ();
  void setAncetres (std::shared_ptr<std::vector<int>> ancetresPere, std::shared_ptr<std::vector<int>> ancetresMere);
};

#endif
