// Generated by dia2code
#ifndef ANIMALMALE__HPP
#define ANIMALMALE__HPP

#include "librairiesQt.hpp"

/// class AnimalMale - 
class AnimalMale : public Animal {
  // Operations
public:
  animalMale ();
  void tuerAnimalMale ();
  void vendreAnimal ();
  void accoupler (std::shared_ptr<Animal> femelle);
};

#endif
