// Generated by dia2code
#ifndef ANIMALFEMELLE__HPP
#define ANIMALFEMELLE__HPP

#include "librairiesQt.hpp"
#include "Animal.hpp"
#include "AnimalMale.hpp"
/// class AnimalFemelle - 
class AnimalFemelle : public Animal {
  // Attributes
private:
  bool isEnceinte;
  std::array<int,2> dateAccouplement;
  std::vector<int> geniteur;
  std::array<int,2> dateDerniereMiseBas;
  // Operations
public:
  AnimalFemelle ();
  void tuerAnimal ();
  void vendreAnimal ();
  void accoupler (bool isEnceinte, std::shared_ptr<Animal> male);
  std::array<Animal, nbEnfantsPortee> mettreBas (bool isEnceinte, std::array<int,2> dateAccouplement, int dureeGestation);
};

#endif
