// Generated by dia2code
#ifndef RENDU__FENETRENOUVELLEBETE__HPP
#define RENDU__FENETRENOUVELLEBETE__HPP


namespace Rendu {

  /// class FenetreNouvelleBete : public QWidget - 
  class FenetreNouvelleBete : public QWidget {
    // Operations
  public:
    FenetreNouvelleBete ();
  };

};

#endif
