// Generated by dia2code
#ifndef RENDU__FENETRENOUVELELEVAGE__HPP
#define RENDU__FENETRENOUVELELEVAGE__HPP

#include "librairiesQt.hpp"

//namespace Rendu {

  /// class FenetreNouvelElevage : public QWidget - 
  class FenetreNouvelElevage : public QWidget {
    // Operations
  public:
    FenetreNouvelElevage ();
    QPushButton* creationBoutonDansLayout (const QString &nom, QWidget* widgetParent, QLayout* layoutParent, const char* signal, QObject* receiver, const char* slot, bool enabled);
  };

//};

#endif
