// Generated by dia2code
#ifndef RACE__HPP
#define RACE__HPP
#include "librairiesQt.hpp"
/// class Race - 
class Race {
  // Attributes
private:
  int idRace;
  QString nomRace;
  std::array<int, 2> esperanceDeVie;
  std::array<int,2> poidsMoyenAdulte;
  std::array<int, 2> ageMoyenMaturite;
  std::array<double, 2> prixNourritureVeterinaire;
  int dureeGestation;
  int dureeEntre2Grossesses;
  int nbEnfantsPortee;
  double prixVenteKilo;
  /// en euros
//  double gainVente_adulte;
  int nbGenerations;
  /// totalise le nombre d'ancêtres à stocker dans le patrimoine génétique, à partir du nombre de générations
  int nbAncetres;
  // Operations
public:
  Race ();
  ~Race ();
  int getIDRace ();
  QString getNomRace ();
  int getEsperanceDeVie (bool sexe);
  int getPoidsMoyenAdulte (bool sexe);
  int getAgeMoyenMaturite (bool sexe);
  double getPrixNourritureVeterinaire (bool sexe);
  int getDureeGestation ();
  int getDureeEntre2Grossesses();
  int getNbEnfantsPortee ();
  double getPrixVenteKilo ();
  //double getGainVente_adulte ();
  int getNbGenerations ();
  int getNbAncetres ();
  void setNomRace (QString &nom);
  void setEsperanceDeVie (bool sexe, int duree_esperancedevie);
  void setPoidsMoyenAdulte (bool sexe, int poids);
  void setAgeMoyenMaturite (bool sexe, int age);
  void setPrixNourritureVeterinaire (bool sexe, double prix);
  void setDureeGestation (int duree);
  void setDureeEntre2Grossesses(int duree);
  void setNbEnfantsPortee (int nbEnfantsPortee);
  void setPrixVenteKilo (double prix);
  //void setGainVente_adulte (double prix);
  void setNbGenerations (int nbGen);
  void setNbAncetres (int nbGenerations);
};

#endif
