// Generated by dia2code
#ifndef TEMPS__HPP
#define TEMPS__HPP

/// class Temps - 
class Temps {
  // Attributes
private:
  int annee;
  int mois;
  // Operations
public:
  Temps();
  Temps(int an, int ms);
  int getAnnee();
  int getMois();
  void setAnnee (int annee);
  void setMois (int mois);
  void upMois ();
  void upAnnee ();
};

#endif
