// Generated by dia2code
#ifndef RENDU__FENETREPRINCIPALE__HPP
#define RENDU__FENETREPRINCIPALE__HPP


/*namespace Rendu {
  class FenetreNouvelleRace : public QWidget;
  class FenetreNouvelElevage : public QWidget;
  class FenetreNouvelleBete : public QWidget;
}//*/
#include "librairiesQt.hpp"

#include "FenetreNouvelleRace.hpp"
#include "FenetreNouvelElevage.hpp"
#include "FenetreNouvelleBete.hpp"//*/


//namespace Rendu {

  /// class FenetrePrincipale : public QMainWindow - 
  class FenetrePrincipale : public QMainWindow{// : public Rendu::FenetreNouvelleRace : public QWidget, public Rendu::FenetreNouvelElevage : public QWidget, public Rendu::FenetreNouvelleBete : public QWidget {
    // Operations
  public:
    FenetrePrincipale ();
  private:
    void creationMenuBar ();
    void creationStatusBar ();
    QMenu*  creationMenu (QMenu * menuPere, const QString  &nomMenuFils);
    QAction* creationActionDansMenu (QMenu* menuPere, const QString &nomAction, QObject* parent, const QKeySequence &shortcut, const char* signal, const QObject* receiver, const char* method);
    QAction* creationActionDansMenu (QMenu* menuPere, const QString &nomAction, QObject* parent, const char* signal, const QObject* receiver, const char* method);
    void creationZoneCentrale ();
    void creationElevage (const QString &nom, QListWidget*  listeParent, QStackedLayout* stackedLayout);
    QPushButton* creationBoutonDansLayout (const QString &nom, QWidget* widgetParent, QLayout* layoutParent, const char* signal, QObject* receiver, const char* slot, bool enabled);
    void creationToolBar ();
  };

//};

#endif
