// Generated by dia2code
#ifndef RENDU__FENETRENOUVELLERACE__HPP
#define RENDU__FENETRENOUVELLERACE__HPP

#include "librairiesQt.hpp"


//namespace Rendu {

  /// class FenetreNouvelleRace : public QWidget - 
  class FenetreNouvelleRace : public QWidget {
    // Operations
  public:
    FenetreNouvelleRace ();
    QPushButton* creationBoutonDansLayout (const QString &nom, QWidget* widgetParent, QLayout* layoutParent, const char* signal, QObject* receiver, const char* slot, bool enabled);
  };

//};

#endif
