// Generated by dia2code
#ifndef FERME__HPP
#define FERME__HPP

#include "librairiesQt.hpp"

/// class Ferme - 
class Ferme {
  // Associations
  Race* elevee;
//  Elevage* composé;
  // Attributes
private:
  std::vector <std::shared_ptr<Elevage>> mesElevages;
  std::vector<std::shared_ptr<Race>> mesRaces;
  double budget;
  double argentEmprunte;
  // Operations
public:
  Ferme ();
  void supprimerFerme ();
  void ajouterElevageListe (std::shared_ptr<Elevage> elevage);
  void supprimerElevageListe (std::shared_ptr<Elevage> elevage);
  void ajouterRaceListe (std::shared_ptr<Race> race);
  void supprimerRaceListe (std::shared_ptr<Race> race);
  double getBudget ();
  void setBudget (double budgetInitial = 0);
  double emprunt (double budget, double sommeEmprunt, double argentEmprunte);
  double remboursementEmprunt (double budget, double sommeRemboursee, double argentEmprunte);
  double plusbudget (double budget, double argentAjoute);
  double moinsbudget (double budget, double argentdepense);
};

#endif
